# Generated by Django 4.2 on 2024-02-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_diagcenter_hospital_image_patient_patientdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagcenter',
            name='pswd',
            field=models.CharField(default='!@#$', max_length=500),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pswd',
            field=models.CharField(default='!@#$', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='pswd',
            field=models.CharField(default='!@#$', max_length=500),
        ),
    ]
