# Generated by Django 4.2 on 2024-02-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_diagcenter_pswd_hospital_pswd_patient_pswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hmail',
            field=models.CharField(default='hospital@gmail.com', max_length=500),
        ),
    ]
