# Generated by Django 4.2 on 2024-02-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_hospital_hmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hnumber',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
