# Generated by Django 4.2 on 2024-02-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_hospital_hnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagcenter',
            name='otp',
            field=models.CharField(default='******', max_length=6),
        ),
        migrations.AddField(
            model_name='hospital',
            name='otp',
            field=models.CharField(default='******', max_length=6),
        ),
        migrations.AddField(
            model_name='patient',
            name='otp',
            field=models.CharField(default='******', max_length=6),
        ),
    ]
