# Generated by Django 3.2.8 on 2024-02-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20240215_1321'),
        ('myapp', '0006_diagcenter_otp_hospital_otp_patient_otp'),
    ]

    operations = [
    ]
