# Generated by Django 3.2.8 on 2024-02-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_merge_20240215_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('hid', models.CharField(max_length=50)),
                ('hname', models.CharField(max_length=50)),
                ('medicine', models.CharField(blank=True, max_length=500)),
                ('time', models.CharField(max_length=50)),
                ('adhno', models.CharField(max_length=12)),
            ],
        ),
    ]
