# Generated by Django 4.2 on 2024-02-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_pres'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='dname',
            field=models.CharField(default='******', max_length=100),
        ),
    ]
