# Generated by Django 4.2 on 2024-02-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_patientdetails_dname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='prescription',
        ),
        migrations.AddField(
            model_name='pdfs',
            name='pdfname',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='pres',
            name='lunch',
            field=models.CharField(default='Anytime', max_length=50),
        ),
    ]
