# Generated by Django 4.2 on 2024-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_patientdetails_prescription_pdfs_pdfname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagcenter',
            name='dnumber',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
