# Generated by Django 4.2 on 2024-02-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_diagcenter_dnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfs',
            name='mid',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='pres',
            name='mid',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
