# Generated by Django 4.2 on 2024-02-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_pdfs_mid_pres_mid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ppdfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhno', models.CharField(max_length=50)),
                ('pdf', models.FileField(blank=True, upload_to='pdfs/')),
                ('pdfname', models.CharField(max_length=50)),
            ],
        ),
    ]
